### ISSUE TITLE
Linux support for ADPICam

### ISSUE THREAD

**Issue by jwlodek** [areaDetector/ADPICam#8]
Hello all,

We are in the process of working with a PI-MTE3, with ADPICam, and we noticed that it says it only builds on windows, and there are no linux binaries for the SDK provided. However, on the PICAM SDK website, it seems to indicate 64 bit linux is a supported architecure:

> PICAM is the driver for controlling all Princeton Instruments cameras and is the platform on which LightField software is built. Teledyne Princeton Instruments also offers the PICAM API, which can be used to directly automate any Princeton Instruments camera using the C run-time. This eliminates any overhead that can occur when communicating through other development environments. It is available for all 64-bit Windows and **Linux** systems.

Source: https://www.princetoninstruments.com/products/software-family/pi-cam

Would it be worthwhile to add support for the linux SDK to this driver?

**Comment by MarkRivers** [comment]
Yes, that should definitely be done.  I am using LightField because all of our applications use an Acton spectrometer, and that can be controlled and displayed directly from LightField.  But having good support for ADPICam in areaDetector would be great.

**Comment by pheest** [comment]
It builds on Linux if the Princeton SDK is installed, by means of the line:
$(PROD_NAME)_SYS_LIBS += picam piac picc pida pidi

I haven't tested it on Linux, however.

I sought to include these libraries as user libraries, but the number required (including dependencies) was prohibitive.
